qtest: testquote.cpp  testquote.h
		g++ -g  -o qtest -I ../../rpcore -I ../../rpchannel/ -I ../../rptrust -I ../../rpquote testquote.cpp   -L ../../../lib   -lrpquote-g -lrptrust-g -lrpchannel-g -lrpcrypto-g
