
# Make for x509AC API
# Daniel Díaz-Sanchez 
# Universidad Carlos III de Madrid


SRCS =  test.c 
        
OBJS =  test.o 

X509ACDIR = ../x509ac/
X509ACINC = $(X509ACDIR)
OPENSSLDIR = ../openssl-0.9.8a/
OPENSSLINC = $(OPENSSLDIR)include
CFLAGS = -I$(OPENSSLINC) -I$(X509ACINC) -m32
CC = gcc
LDFLAGS = 


all: app

app: $(OBJS)	
	$(CC)  -L$(OPENSSLDIR) -lcrypto -L$(X509ACDIR) -lx509ac -o test $(OBJS)	
	@echo "********* IN ORDER TO TEST THE LIBRARY ***************"
	@echo in bash, run "export LD_LIBRARY_PATH=../x509ac/" and then 
	@echo test library with ./test
clean:
	rm -f *.o
	rm -f *.c~
	rm -f *.h~


