testapp: testapp.cpp ../../rpchannel/tcpchan.cpp ../../rpchannel/tcpchan.h
		g++ -g testapp.cpp  -I ../../rpcore -I ../../rpchannel/ -I ../../rptrust -L ../../../lib -lrptrust-g -lrpchannel-g -lrpcrypto-g -o testapp
