import os
XAPI_PROXYSERVER_IP = os.environ['IP_ADDRESS']
XAPI_SERVER_IP = os.environ['IP_ADDRESS']
XAPI_SERVER_PORT = 80
XMLRPC_PROXYSERVER_PORT = 8080
RPCORE_PORT=16005
IMAGE_TMPFS_DIR = '/image_tmpfs/'

